language: cpp
compiler:
  - gcc

install:
  - wget http://tarantool.org/dist/public.key -O | sudo apt-key add
  - export release=`lsb_release -c -s`
  - |
    cat > /etc/apt/sources.list.d/tarantool.list <<- EOF
    deb http://tarantool.org/dist/master/ubuntu/ $release main
    deb-src http://tarantool.org/dist/master/ubuntu/ $release main
    EOF
  - sudo apt-get update > /dev/null
  - sudo apt-get -q install tarantool tarantool-dev

script:
  - cmake . -DCMAKE_BUILD_TYPE=RelWithDebugInfo
  - make
  - make test
